[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pabulib-checker"
version = "0.2.0"
description = "A Python library for validating files in the PB (Pabulib) format, ensuring compliance with the standards described at pabulib.org/format."
authors = [
    { name = "Ignacy Janiszewski", email = "ignacy.janiszewsk@uj.edu.pl" }
]
license = "MIT"
dependencies = ["pycountry>=24.6.1"]
requires-python = ">=3.7"
readme = "README.md"
keywords = ["checker", "file validation", "python", "pabulib"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pabulib/checker"
Repository = "https://github.com/pabulib/checker"
Issues = "https://github.com/pabulib/checker/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["pabulib*", "pabulib_helpers*"]